export const GAME_INIT_MATCH = 'GAME_INIT_MATCH';
export const GAME_NEXT_MATCH = 'GAME_NEXT_MATCH';
export const GAME_SET_PRIZE = 'GAME_SET_PRIZE';

export const ACTION_GAME_EXPECTATION = 'ACTION_GAME_EXPECTATION'; 